# all math operators are right associative because I'm a hack

num    = whatever strtold accepts
string = /"([^\\](\\[nt"]))*"/
id     = /[a-zA-Z][a-zA-Z0-9_]*/
nl     = \n

program = $expression_stmt*

expression_stmt =
    | $expression $nl
    | $expression $eof

expression =
    | set $lvalue = $expression
    | $orexp

lvalue = $var

orexp =
    | $andexp or $orexp
    | $andexp

andexp =
    | $compexp and $andexp
    | $andexp

compop = < | <= | = | > | >=

compexp =
    | $addexp $compop $addexp
    | $addexp

addop = + / -

addexp =
    | $mulexp $addop $addexp
    | $mulexp

mulop = * | /

mulexp =
    | $prefix $mulop $mulexp
    | $prefix

prefix =
    | not $prefix
    | - $prefix
    | $base

base =
    | ( $expression )
    | $id
    | $num
    | $string
    | true
    | false
    | unit
