# all math operators are right associative because I'm a hack

num    = whatever strtold accepts
string = /"([^\\](\\[nt"]))*"/
id     = /[a-zA-Z_][a-zA-Z0-9_]*/
nl     = \n

program = $expression_stmt*

expression_stmt =
    | $expression $nl+
    | $expression $nl* $eof

expression =
    | set $lvalue = $expression
    | $concatexp

lvalue = $var

concatexp =
    | $orexp .. $concatexp
    | $orexp

orexp =
    | $andexp or $orexp
    | $andexp

andexp =
    | $compexp and $andexp
    | $andexp

compop = < | <= | = | > | >=

compexp =
    | $addexp $compop $addexp
    | $addexp

addop = + / -

addexp =
    | $mulexp $addop $addexp
    | $mulexp

mulop = * | /

mulexp =
    | $prefix $mulop $mulexp
    | $prefix

prefix =
    | not $prefix
    | - $prefix
    | $base

base =
    | ( $expression )
    | $id
    | $num
    | $string
    | true
    | false
    | unit
    | @builtin ( $arglist )
    | begin $nl ($expression $nl)* end
    | begin $expression end
