I haven't documented all the places where whitespace sensitivity
gets "turned off", i.e where arbitrary newlines are allowed

num    = whatever strtold accepts
string = /"([^\\](\\[nt"]))*"/
id     = /[a-zA-Z_][a-zA-Z0-9_]*/
nl     = \n

program = $expression_stmt*

expression_stmt =
    | $expression $nl+
    | $expression $nl* $eof

expression =
    | set $lvalue = $expression
    | $concatexp

lvalue =
    | $var
    | $lvalue [ $expression ]

concatexp =
    | $concatexp .. $orexp
    | $orexp

orexp =
    | $andexp or $orexp
    | $andexp

andexp =
    | $compexp and $andexp
    | $andexp

compop = < | <= | = | > | >=

compexp =
    | $addexp $compop $addexp
    | $addexp

addop = + / -

addexp =
    | $addexp $addop $mulexp
    | $mulexp

mulop = * | /

mulexp =
    | $mulexp $mulop $powexp
    | $powexp

powexp =
    | $prefix ^ $powexp
    | $prefix

prefix =
    | not $prefix
    | - $prefix
    | $postfix

postfix =
    | $postfix ( $arglist )
    | $postfix [ $expression ]
    | $base

arglist =
    | <empty>
    | $expression , $arglist
    | $expression ,?

base =
    | ( $expression )
    | $id
    | $num
    | $string
    | true
    | false
    | unit
    | @builtin
    | if $expression then $body (elif $body)* (else $body)? end
    | while $expression do $body end
    | func ( $fnArgList ) $body end
    | begin $body end

body =
    | $expression
    | $nl+ ($expression $nl+)+
